In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import statsmodels.api as sm
import sklearn as s
from sklearn import datasets,linear_model
from sklearn.linear_model import lasso_path
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
#from matplotlib import pyplot as plt

df=pd.read_csv('E:\Project_Data/Data.csv',sep=',',header=0)
df = df[df.test_time >= 0] #removing data with negative testtime
df.describe()

age    test_time  motor_UPDRS  total_UPDRS  Jitter(Absolute)  \
count  5863.000000  5863.000000  5863.000000  5863.000000       5863.000000   
mean     64.814771    93.061538    21.289655    29.014090          0.000044   
std       8.827750    53.320896     8.133419    10.709966          0.000036   
min      36.000000     0.395830     5.037700     7.000000          0.000002   
25%      58.000000    47.335500    15.000000    21.362000          0.000022   
50%      65.000000    91.754000    20.871000    27.522000          0.000035   
75%      72.000000   138.460000    27.594000    36.400500          0.000053   
max      85.000000   215.490000    39.511000    54.992000          0.000446   

        Jitter:RAP  Jitter:PPQ5   Jitter:DDP      Shimmer  Shimmer(dB)  \
count  5863.000000  5863.000000  5863.000000  5863.000000  5863.000000   
mean      0.002988     0.003278     0.008965     0.034038     0.311012   
std       0.003126     0.003734     0.009378     0.025836     0.230310   
min       0.000330     0.000430     0.000980     0.003060     0.026000   
25%       0.001580     0.001825     0.004730     0.019110     0.175000   
50%       0.002250     0.002490     0.006750     0.027530     0.253000   
75%       0.003290     0.003470     0.009880     0.039775     0.365000   
max       0.057540     0.069560     0.172630     0.268630     2.107000   

       Shimmer:APQ3  Shimmer:APQ5  Shimmer:APQ11  Shimmer:DDA          NHR  \
count   5863.000000   5863.000000    5863.000000  5863.000000  5863.000000   
mean       0.017157      0.020149       0.027489     0.051470     0.032126   
std        0.013237      0.016672       0.020002     0.039710     0.059735   
min        0.001610      0.001940       0.002490     0.004840     0.000286   
25%        0.009280      0.010790       0.015660     0.027830     0.010953   
50%        0.013700      0.015940       0.022710     0.041110     0.018448   
75%        0.020605      0.023775       0.032725     0.061805     0.031464   
max        0.162670      0.167020       0.275460     0.488020     0.748260   

               HNR         RPDE          DFA          PPE  Jitter(Percent)  
count  5863.000000  5863.000000  5863.000000  5863.000000      5863.000000  
mean     21.679527     0.541423     0.653252     0.219618         0.006156  
std       4.292521     0.101024     0.070955     0.091494         0.005628  
min       1.659000     0.151020     0.514040     0.021983         0.000830  
25%      19.404000     0.469695     0.596100     0.156385         0.003580  
50%      21.917000     0.542250     0.643550     0.205560         0.004900  
75%      24.445500     0.614045     0.711480     0.264590         0.006800  
max      37.875000     0.966080     0.865600     0.731730         0.099990

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
X = df.drop(["motor_UPDRS","total_UPDRS", "Jitter(Percent)", "Jitter:RAP", "Jitter:PPQ5", "Jitter:DDP", "Shimmer", "Shimmer(dB)", "Shimmer:APQ3", "Shimmer:APQ5", "Shimmer:DDA","NHR","RPDE","DFA","PPE"], axis=1)
X.head()

age  test_time  Jitter(Absolute)  Shimmer:APQ11     HNR
0   72     5.6431          0.000034        0.01662  21.640
1   72    12.6660          0.000017        0.01689  27.183
2   72    19.6810          0.000025        0.01458  23.047
3   72    25.6470          0.000027        0.01963  24.445
4   72    33.6420          0.000020        0.01819  26.126

In [18]:
#Y = df.drop(["motor_UPDRS","total_UPDRS", "Jitter(Percent)", "Jitter:RAP", "Jitter:PPQ5", "Jitter:DDP", "Shimmer", "Shimmer(dB)", "Shimmer:APQ3", "Shimmer:APQ5", "Shimmer:DDA","age","test_time","Jitter(Absolute)","Shimmer:APQ11","HNR"], axis=1)
Y= df["NHR"]
Y.head()

0    0.014290
1    0.011112
2    0.020220
3    0.027837
4    0.011625
Name: NHR, dtype: float64

In [19]:
# Converts target and features to numpy arrays for sklearn API
target_y = Y.as_matrix()
features_x = X.as_matrix()

C:\Users\Namrata\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  
C:\Users\Namrata\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  This is separate from the ipykernel package so we can avoid doing imports until


In [20]:
# Split into train and test sets
X_train, X_test, Y_train, Y_test = train_test_split(features_x, target_y, test_size=0.18, random_state=0)


In [21]:
lm = linear_model.LinearRegression() #LinearRegression apply
model = lm.fit(X_train, Y_train) #actual "learning" happens here
predictions = lm.predict(X_test)
predictions[0:5]

array([-0.00406305,  0.02980486,  0.01086987,  0.03852816, -0.00650895])

In [22]:
from sklearn import model_selection
from sklearn.model_selection import train_test_split,cross_val_score
lm1=linear_model.LinearRegression()  #LinearRegression
s_lm=model_selection.cross_val_score(lm1,X_train,Y_train,scoring="r2",cv=5)
s_lm.mean()

0.6289670587329208

In [23]:
# import the regressor 
from sklearn.tree import DecisionTreeRegressor #DecisionTreeRegression

# create a regressor object 
regressor = DecisionTreeRegressor(random_state = 0) 

# fit the regressor with X and Y data 
regressor.fit(X_train, Y_train)
predictions1 = regressor.predict(X_test)
predictions1[0:5]

array([0.0156445, 0.02084  , 0.017767 , 0.019494 , 0.005883 ])

In [24]:
from sklearn import tree #DecisionTreeRegression
tr1=tree.DecisionTreeRegressor()
s_tr=model_selection.cross_val_score(tr1,X_train,Y_train,scoring="r2",cv=5)
s_tr.mean()

0.862575721856372

In [25]:
from sklearn.metrics import r2_score #DecisionTreeR2
r2_score(Y_test, predictions1)

0.8436806701481143

In [31]:
from sklearn.metrics import mean_squared_error #DecisionTreeRMSE
from math import sqrt

rms2 = sqrt(mean_squared_error(Y_test, predictions1))
print(rms2)


0.02087179943941631


In [32]:
from sklearn import metrics #DecisionTreeRegressionMAE
from sklearn.metrics import mean_absolute_error
mean_absolute_error(Y_test, predictions1)

0.01115069700689935

In [33]:
from sklearn.metrics import explained_variance_score #The best possible score is 1.0, lower values are worse.
explained_variance_score(Y_test, predictions1) #DecisionTreeEVS

0.8436835951666449

In [26]:
from sklearn.ensemble import RandomForestRegressor #RandomForestRegression

regressor1 = RandomForestRegressor(n_estimators=800, random_state=1)  
regressor1.fit(X_train, Y_train)  
predictions2= regressor1.predict(X_test)
predictions2[0:5]

array([0.01228921, 0.02019452, 0.01515653, 0.02771991, 0.00835362])

In [13]:
from sklearn import ensemble
rnf1=ensemble.RandomForestRegressor()
s_rnf=model_selection.cross_val_score(rnf1,X_train,Y_train,scoring="r2",cv=5)
s_rnf.mean()

C:\Users\Namrata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Namrata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Namrata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Namrata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Namrata\Anaconda3\lib\site-packages\sklearn\ensemble\forest

0.7366429967412382

In [27]:
from sklearn.preprocessing import PolynomialFeatures #PolynomialRegression
from sklearn.linear_model import LinearRegression
# PolynomialFeatures (prepreprocessing)
poly = PolynomialFeatures(degree=2)
X_ = poly.fit_transform(X_train)
X_test_ = poly.fit_transform(X_test)
# Instantiate
lg = LinearRegression()

# Fit
lg.fit(X_, Y_train)

# Obtain coefficients
lg.coef_
# Predict
predictions3=lg.predict(X_test_)
predictions3[0:5]

array([0.01398055, 0.02211727, 0.00966415, 0.02619989, 0.01307886])

In [28]:
from sklearn.metrics import r2_score #PolynomialRegressionR2Score
r2_score(Y_test, predictions3)

0.860700063853097

In [34]:
from sklearn.metrics import mean_squared_error #PolynomialRMSE
from math import sqrt

rms4 = sqrt(mean_squared_error(Y_test, predictions3))
print(rms4)


0.019702848107635926


In [35]:
from sklearn import metrics #PolynomialRegressionMAE
from sklearn.metrics import mean_absolute_error
mean_absolute_error(Y_test, predictions3)

0.011547711317927763

In [37]:
from sklearn.metrics import explained_variance_score #The best possible score is 1.0, lower values are worse.
explained_variance_score(Y_test, predictions3) #Polynomial EVS

0.8608201960030268

In [29]:
from sklearn.neighbors import KNeighborsRegressor #KNeighboursRegression
neigh = KNeighborsRegressor(n_neighbors=2)
neigh.fit(X_train, Y_train) 
KNeighborsRegressor(...)
predictions4=(neigh.predict(X_test))
predictions4[0:5]

array([0.0088905, 0.030022 , 0.015502 , 0.035826 , 0.009835 ])

In [30]:
from sklearn import neighbors #KNeighborsRegression
knn1=neighbors.KNeighborsRegressor()
s_knn=model_selection.cross_val_score(knn1,X_train,Y_train,scoring="r2",cv=5)
s_knn.mean()

0.7699736051825455