In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import statsmodels.api as sm
import sklearn as s
from sklearn import datasets,linear_model
from sklearn.linear_model import lasso_path
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
#from matplotlib import pyplot as plt

df=pd.read_csv('E:\Project_Data/Data.csv',sep=',',header=0)
df = df[df.test_time >= 0] #removing data with negative testtime
df.describe()

age    test_time  motor_UPDRS  total_UPDRS  Jitter(Absolute)  \
count  5863.000000  5863.000000  5863.000000  5863.000000       5863.000000   
mean     64.814771    93.061538    21.289655    29.014090          0.000044   
std       8.827750    53.320896     8.133419    10.709966          0.000036   
min      36.000000     0.395830     5.037700     7.000000          0.000002   
25%      58.000000    47.335500    15.000000    21.362000          0.000022   
50%      65.000000    91.754000    20.871000    27.522000          0.000035   
75%      72.000000   138.460000    27.594000    36.400500          0.000053   
max      85.000000   215.490000    39.511000    54.992000          0.000446   

        Jitter:RAP  Jitter:PPQ5   Jitter:DDP      Shimmer  Shimmer(dB)  \
count  5863.000000  5863.000000  5863.000000  5863.000000  5863.000000   
mean      0.002988     0.003278     0.008965     0.034038     0.311012   
std       0.003126     0.003734     0.009378     0.025836     0.230310   
min       0.000330     0.000430     0.000980     0.003060     0.026000   
25%       0.001580     0.001825     0.004730     0.019110     0.175000   
50%       0.002250     0.002490     0.006750     0.027530     0.253000   
75%       0.003290     0.003470     0.009880     0.039775     0.365000   
max       0.057540     0.069560     0.172630     0.268630     2.107000   

       Shimmer:APQ3  Shimmer:APQ5  Shimmer:APQ11  Shimmer:DDA          NHR  \
count   5863.000000   5863.000000    5863.000000  5863.000000  5863.000000   
mean       0.017157      0.020149       0.027489     0.051470     0.032126   
std        0.013237      0.016672       0.020002     0.039710     0.059735   
min        0.001610      0.001940       0.002490     0.004840     0.000286   
25%        0.009280      0.010790       0.015660     0.027830     0.010953   
50%        0.013700      0.015940       0.022710     0.041110     0.018448   
75%        0.020605      0.023775       0.032725     0.061805     0.031464   
max        0.162670      0.167020       0.275460     0.488020     0.748260   

               HNR         RPDE          DFA          PPE  Jitter(Percent)  
count  5863.000000  5863.000000  5863.000000  5863.000000      5863.000000  
mean     21.679527     0.541423     0.653252     0.219618         0.006156  
std       4.292521     0.101024     0.070955     0.091494         0.005628  
min       1.659000     0.151020     0.514040     0.021983         0.000830  
25%      19.404000     0.469695     0.596100     0.156385         0.003580  
50%      21.917000     0.542250     0.643550     0.205560         0.004900  
75%      24.445500     0.614045     0.711480     0.264590         0.006800  
max      37.875000     0.966080     0.865600     0.731730         0.099990

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
X = df.drop(["motor_UPDRS","total_UPDRS", "Jitter(Percent)", "Jitter:RAP", "Jitter:PPQ5", "Jitter:DDP", "Shimmer", "Shimmer(dB)", "Shimmer:APQ3", "Shimmer:APQ5", "Shimmer:DDA","NHR","RPDE","DFA","PPE"], axis=1)
X.head()

age  test_time  Jitter(Absolute)  Shimmer:APQ11     HNR
0   72     5.6431          0.000034        0.01662  21.640
1   72    12.6660          0.000017        0.01689  27.183
2   72    19.6810          0.000025        0.01458  23.047
3   72    25.6470          0.000027        0.01963  24.445
4   72    33.6420          0.000020        0.01819  26.126

In [6]:
#Y = df.drop(["motor_UPDRS","total_UPDRS", "Jitter(Percent)", "Jitter:RAP", "Jitter:PPQ5", "Jitter:DDP", "Shimmer", "Shimmer(dB)", "Shimmer:APQ3", "Shimmer:APQ5", "Shimmer:DDA","age","test_time","Jitter(Absolute)","Shimmer:APQ11","HNR"], axis=1)
Y= df["RPDE"]
Y.head()

0    0.41888
1    0.43493
2    0.46222
3    0.48730
4    0.47188
Name: RPDE, dtype: float64

In [7]:
# Converts target and features to numpy arrays for sklearn API
target_y = Y.as_matrix()
features_x = X.as_matrix()

C:\Users\Namrata\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  
C:\Users\Namrata\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  This is separate from the ipykernel package so we can avoid doing imports until


In [8]:
# Split into train and test sets
X_train, X_test, Y_train, Y_test = train_test_split(features_x, target_y, test_size=0.18, random_state=0)


In [9]:
lm = linear_model.LinearRegression() #LinearRegression apply
model = lm.fit(X_train, Y_train) #actual "learning" happens here
predictions = lm.predict(X_test)
predictions[0:5]

array([0.49341095, 0.55899874, 0.49454856, 0.57107274, 0.48742895])

In [10]:
from sklearn import model_selection
from sklearn.model_selection import train_test_split,cross_val_score
lm1=linear_model.LinearRegression()  #LinearRegression
s_lm=model_selection.cross_val_score(lm1,X_train,Y_train,scoring="r2",cv=5)
s_lm.mean()

0.4498140310262498

In [26]:
from sklearn.metrics import explained_variance_score #The best possible score is 1.0, lower values are worse.
explained_variance_score(Y_test, predictions) #linearRegressionEVS

0.4420629004566756

In [11]:
# import the regressor 
from sklearn.tree import DecisionTreeRegressor #DecisionTreeRegression

# create a regressor object 
regressor = DecisionTreeRegressor(random_state = 0) 

# fit the regressor with X and Y data 
regressor.fit(X_train, Y_train)
predictions1 = regressor.predict(X_test)
predictions1[0:5]

array([0.58058, 0.5423 , 0.45439, 0.49221, 0.39024])

In [12]:
from sklearn import tree #DecisionTreeRegression
tr1=tree.DecisionTreeRegressor()
s_tr=model_selection.cross_val_score(tr1,X_train,Y_train,scoring="r2",cv=5)
s_tr.mean()

0.23499375794084462

In [27]:
from sklearn.metrics import explained_variance_score #The best possible score is 1.0, lower values are worse.
explained_variance_score(Y_test, predictions1) #DecisionTreeEVS

0.30914853023538746

In [30]:
from sklearn.ensemble import RandomForestRegressor #RandomForestRegression

regressor1 = RandomForestRegressor(n_estimators=1000, random_state=1)  
regressor1.fit(X_train, Y_train)  
predictions2= regressor1.predict(X_test)
predictions2[0:5]

array([0.52662525, 0.63167962, 0.49167748, 0.56024296, 0.42256339])

In [31]:
from sklearn import ensemble
rnf1=ensemble.RandomForestRegressor()
s_rnf=model_selection.cross_val_score(rnf1,X_train,Y_train,scoring="r2",cv=5)
s_rnf.mean()

C:\Users\Namrata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Namrata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Namrata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Namrata\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Namrata\Anaconda3\lib\site-packages\sklearn\ensemble\forest

0.5539927960390367

In [33]:
from sklearn.metrics import explained_variance_score #The best possible score is 1.0, lower values are worse.
explained_variance_score(Y_test, predictions2) #Random Forest EVS

0.6072167533463075

In [16]:
from sklearn.preprocessing import PolynomialFeatures #PolynomialRegression
from sklearn.linear_model import LinearRegression
# PolynomialFeatures (prepreprocessing)
poly = PolynomialFeatures(degree=2)
X_ = poly.fit_transform(X_train)
X_test_ = poly.fit_transform(X_test)
# Instantiate
lg = LinearRegression()

# Fit
lg.fit(X_, Y_train)

# Obtain coefficients
lg.coef_
# Predict
predictions3=lg.predict(X_test_)
predictions3[0:5]

array([0.47901657, 0.5536045 , 0.53578868, 0.56034488, 0.46322673])

In [17]:
from sklearn.metrics import explained_variance_score #The best possible score is 1.0, lower values are worse.
explained_variance_score(Y_test, predictions3) #Polynomial EVS

0.47385265695070644

In [18]:
from sklearn.neighbors import KNeighborsRegressor #KNeighboursRegression
neigh = KNeighborsRegressor(n_neighbors=2)
neigh.fit(X_train, Y_train) 
KNeighborsRegressor(...)
predictions4=(neigh.predict(X_test))
predictions4[0:5]

array([0.59148 , 0.5845  , 0.530275, 0.615125, 0.537525])

In [19]:
from sklearn import neighbors #KNeighborsRegression
knn1=neighbors.KNeighborsRegressor()
s_knn=model_selection.cross_val_score(knn1,X_train,Y_train,scoring="r2",cv=5)
s_knn.mean()

0.4849631125445228

In [29]:
from sklearn.metrics import explained_variance_score #The best possible score is 1.0, lower values are worse.
explained_variance_score(Y_test, predictions4) #KNN EVS

0.44469250584592757

In [21]:
# Scale features
min_max_scaler = MinMaxScaler()
X_train_minmax = min_max_scaler.fit_transform(X_train)
X_test_minmax = min_max_scaler.fit_transform(X_test)

In [22]:
from sklearn.svm import SVR
from sklearn.model_selection import GridSearchCV, RandomizedSearchCV
from scipy.stats import randint, expon

# Hyperparameter optimization: 
# Use randomized search for drastically faster param tuning. 
# TODO: Compare with kernel ridge regression and other algos

params = {'C': expon(scale=100), 'gamma': expon(scale=.1),
  'kernel': ['linear', 'rbf']}

svr = SVR()

n_iter_search = 200
clf = RandomizedSearchCV(svr, param_distributions=params,
                                   n_iter=n_iter_search)

clf.fit(X_train_minmax, Y_train)

clf.best_estimator_

y_pred = clf.predict(X_test_minmax)

C:\Users\Namrata\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


In [23]:
from sklearn.metrics import mean_squared_error #SVMMAE
from math import sqrt

rms6 = sqrt(mean_squared_error(Y_test, y_pred))
print(rms6)


0.07742086221145403


In [24]:
from sklearn.metrics import r2_score #SVM R2Score
r2_score(Y_test, y_pred)

0.40709339572530256

In [25]:
from sklearn.metrics import explained_variance_score #The best possible score is 1.0, lower values are worse.
explained_variance_score(Y_test, y_pred) #SVM EVS

0.4592382805745495